name: Run tests

on:
  - push
  - pull_request

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  test-on-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12 # Just because it matches the Ubuntu 22.04 default
          cache: npm
      - name: Install other dependencies
        run: bin/setup
      - name: Build
        run: bin/build
      - name: Test
        run: bin/test
      - name: Upload 'bin' artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: dist/bin
      - name: Upload 'coverage/' artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/
